// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMAqQ-OQ2L34-6JlnQCASlP1YxhXaiaT4',
    appId: '1:116764537733:web:cc8475294cd21f346e4aec',
    messagingSenderId: '116764537733',
    projectId: 'ctgapp-2dc42',
    authDomain: 'ctgapp-2dc42.firebaseapp.com',
    storageBucket: 'ctgapp-2dc42.firebasestorage.app',
    measurementId: 'G-1ZEYJH8061',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQVWtM_daUeAtOJTen8d01GsCQQtY6JXw',
    appId: '1:116764537733:android:98cb48e9499f67816e4aec',
    messagingSenderId: '116764537733',
    projectId: 'ctgapp-2dc42',
    storageBucket: 'ctgapp-2dc42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH5q9_7YgDu0jwfPHEbrw4ngc7sjIW6XQ',
    appId: '1:116764537733:ios:6ac892a1fed64e836e4aec',
    messagingSenderId: '116764537733',
    projectId: 'ctgapp-2dc42',
    storageBucket: 'ctgapp-2dc42.firebasestorage.app',
    androidClientId: '116764537733-98puderioc89e3nsvq3qbis9f4ji1as1.apps.googleusercontent.com',
    iosClientId: '116764537733-cod6f7465gqfmjbraruffctn0ln843f5.apps.googleusercontent.com',
    iosBundleId: 'com.ctg.ctgApp',
  );

}